### ISSUE TITLE
dcraw is not working for raw images from rawcam?

### ISSUE THREAD

**Issue by Terminus-IMRC** [6by9/RPiTest#2]
Since 14c1c84ae9ac3c2aa7c8b4d6693b67f9eb038b5f ("DCRAW: Bump to Version 9.26"), dcraw doesn't seem to be working for raw images from rawcam. It was working until 59a41d4da93cc07e96c6d64103ff7405c2b0333b.
Procedure to reproduce:

```
$ git clone https://github.com/6by9/firmware -b rawcam
$ cd firmware; cmake .; make
$ bin/raspiraw
$ git clone https://github.com/6by9/RPiTest
$ cd RPiTest/dcraw; ./buildme
$ ./dcraw -v raw0001.raw
```

The output is, until 59a41d4da93cc07e96c6d64103ff7405c2b0333b:

```
Loading OmniVision 2611x1944 image from raw0001.raw ...
Scaling with darkness 0, saturation 1023, and
multipliers 1.322127 1.000000 1.205187 1.000000
AHD interpolation...
Converting to sRGB colorspace...
Writing data to raw0001.ppm ...
```

and since 14c1c84ae9ac3c2aa7c8b4d6693b67f9eb038b5f:

```
Cannot decode file raw0001.raw
```

Am I wrong in dcraw's options etc.?

Thanks.

**Comment by 6by9** [comment]
It'll be predominantly https://github.com/6by9/RPiTest/commit/14c1c84ae9ac3c2aa7c8b4d6693b67f9eb038b5f#diff-f29c1da0e3b6207b99ae3e301dcb547aL7743

I hadn't consciously made it support the images from rawcam. AFAIK dcraw has no way to set width/height/stride/Bayer order off the command line, and the output of rawcam has no data beyond the raw image data so there is no metadata in the file.
The only "nice" option I can see is to create a JPEG header with the relevant parameters in to determine it is a Pi capture, then a constructed BRCM header block which describes the raw block that is to follow. The capture app would then need to save that before the raw data for each frame. There are now too many options supported from the Pi camera to do otherwise.

I am hoping that the recent changes will get merged into the upstream version, so having a hack to assume that everything is an OV5647 2592x1944 raw image is not acceptable.

**Comment by Terminus-IMRC** [comment]
Thank you for your kind reply! I see.

**Comment by Terminus-IMRC** [comment]
So I have another question: which program are you using to decode raw images from rawcam?

**Comment by 6by9** [comment]
> So I have another question: which program are you using to decode raw images from rawcam?

The simple answer is I haven't for a while.

HDMI in using the Toshiba TC358743 bridge chip spits out RGB888, and the
vc.ril.isp component is converting that happily to YUV.
Likewise the latest updates to
https://github.com/6by9/userland/blob/rawcam/host_applications/linux/apps/raspicam/raspiraw.c
are now plumbing rawcam to vc.ril.isp instead of capturing the images to a
file

I did have a quick play trying to apply a minimal JPEG and raw header on
the front of the output from rawcam, but failed to get it to play ball. The
padding in the raw output of rawcam doesn't necessarily match that appended
to the JPEG, so those are likely just wrong.
A quick look at the dcraw code again, the first code lines of identify()
read 32 bytes of the file and do memcmp for various strings. Using that
with raspiraw writing the BRCM header appropriately should be pretty
trivial.

I have other tasks in progress at the moment, but adding that support in
would be a useful thing. If you fancy doing it, then say and I'll leave you
to it, otherwise I'll see if I get a spare hour some time soon.

**Comment by 6by9** [comment]
OK, I'm too easily distracted. I'm playing now with dcraw to tidy up the parsing...

**Comment by 6by9** [comment]
OK, dcraw should now take a file that starts at the 'BRCM' tag. You can test by using ```tail -c 10270208 input.jpg > output.raw``` for a standard mode2 IMX219 capture, or use appropriate offsets for the other modes/sensors.

The latest https://github.com/6by9/userland/tree/rawcam has two #defines near the top of raspiraw.c, ```CAPTURE``` and ```WRITE_HEADER```. 
With ```CAPTURE 0``` it connects rawcam to isp to video_render. (Default)
With ```CAPTURE 1``` and ```WRITE_HEADER 0``` you get the original behaviour.
With ```CAPTURE 1``` and ```WRITE_HEADER 1``` you should get a raw file with appropriate header such that this latest dcraw can parse it. Hopefully it gets the Bayer order correct. In theory it will do the correct settings for bits/pixel values other than 10, but dcraw won't take them currently (it could be made to).

Please reopen if you find something that doesn't work.
